// DEF_FUNC(name, priority, hasOneArg, string, length, code)

DEF_FUNC(ADD_OPERATION,     0, false, "+",      1, return _diffAddSub  (node, oldNode, texFile))
DEF_FUNC(SUB_OPERATION,     0, false, "-",      1, return _diffAddSub  (node, oldNode, texFile))
DEF_FUNC(MUL_OPERATION,     1, false, "*",      1, return _diffMultiply(node, oldNode, texFile))
DEF_FUNC(DIV_OPERATION,     1, false, "/",      1, return _diffDivide  (node, oldNode, texFile))
DEF_FUNC(POWER_OPERATION,   2, false, "^",      1, return _diffPower   (node, oldNode, texFile))
DEF_FUNC(SIN_OPERATION,     3, true,  "sin",    3, return _diffSin     (node, oldNode, texFile))
DEF_FUNC(COS_OPERATION,     3, true,  "cos",    3, return _diffCos     (node, oldNode, texFile))
DEF_FUNC(TAN_OPERATION,     3, true,  "tan",    3, return _diffTan     (node, oldNode, texFile))
DEF_FUNC(ARC_SIN_OPERATION, 3, true,  "arcsin", 6, return _diffArcsin  (node, oldNode, texFile))
DEF_FUNC(ARC_COS_OPERATION, 3, true,  "arccos", 6, return _diffArccos  (node, oldNode, texFile))
DEF_FUNC(ARC_TAN_OPERATION, 3, true,  "arctan", 6, return _diffArctan  (node, oldNode, texFile))
DEF_FUNC(EXP_OPERATION,     3, true,  "exp",    3, return _diffExp     (node, oldNode, texFile))
DEF_FUNC(LN_OPERATION,      3, true,  "ln",     2, return _diffLn      (node, oldNode, texFile))
